AWSTemplateFormatVersion: '2010-09-09'
Description: 'VPC, subnets, and route tables for n8n'

Parameters:
  VpcCidr:
    Type: String

  PublicSubnetCIDRs:
    Type: List<String>

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:             !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: VPCGatewayAttachment
    Properties:
      RouteTableId         : !Ref PublicRouteTable
      DestinationCidrBlock : '0.0.0.0/0'
      GatewayId            : !Ref InternetGateway

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId                  : !Ref VPC
      CidrBlock              : !Select [ 0, !Ref PublicSubnetCIDRs ]
      AvailabilityZone       : !Select [ 0, !GetAZs '' ]
      MapPublicIpOnLaunch    : true

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId                  : !Ref VPC
      CidrBlock              : !Select [ 1, !Ref PublicSubnetCIDRs ]
      AvailabilityZone       : !Select [ 1, !GetAZs '' ]
      MapPublicIpOnLaunch    : true

  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId     : !Ref PublicSubnet1
      RouteTableId : !Ref PublicRouteTable

  PublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId     : !Ref PublicSubnet2
      RouteTableId : !Ref PublicRouteTable

Outputs:
  VpcId:
    Value: !Ref VPC

  PublicSubnetIds:
    Value: !Join [ ',', [ !Ref PublicSubnet1, !Ref PublicSubnet2 ] ]
