# outputs.yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: Aggregate key outputs from all n8n nested stacks

Parameters:
  VpcId:
    Type: String
  PublicSubnetIds:
    Type: List<String>
  PrivateSubnetIds:
    Type: List<String>
  ALBSecurityGroupId:
    Type: String
  EC2SecurityGroupId:
    Type: String
  RDSSecurityGroupId:
    Type: String
  InstanceProfileName:
    Type: String

Resources:
  Vpc:
    Type: AWS::CloudFormation::WaitConditionHandle

Outputs:
  VpcId:
    Description: VPC ID
    Value: !Ref VpcId

  PublicSubnetIds:
    Description: Public Subnet IDs
    Value: !Join [ ',', !Ref PublicSubnetIds ]

  PrivateSubnetIds:
    Description: Private Subnet IDs
    Value: !Join [ ',', !Ref PrivateSubnetIds ]

  ALBSecurityGroupId:
    Description: ALB Security Group ID
    Value: !Ref ALBSecurityGroupId

  EC2SecurityGroupId:
    Description: EC2 Security Group ID
    Value: !Ref EC2SecurityGroupId

  RDSSecurityGroupId:
    Description: RDS Security Group ID
    Value: !Ref RDSSecurityGroupId

  EC2InstanceProfile:
    Description: Instance Profile for n8n EC2s
    Value: !Ref InstanceProfileName
