# security.yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: Security Groups for n8n ALB, EC2, and RDS

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC in which to create security groups
  SSHCidr:
    Type: String
    Default: 0.0.0.0/0
    Description: CIDR range for SSH to EC2 (for debugging)

Resources:
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "EC2 security group for n8n backend"
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5678
          ToPort: 5678
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SSHCidr
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-ec2-sg"

Outputs:
  EC2SecurityGroupId:
    Description: SG for n8n EC2 instances
    Value: !Ref EC2SecurityGroup
